//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> age { get; set; }
        public string address { get; set; }
        public string password { get; set; }
        public Nullable<int> role_id { get; set; }
        public string email { get; set; }
    
        public virtual role role { get; set; }
    }
}
